apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-mysql
  template:
    metadata:
      labels:
        app: laravel-mysql
    spec:
      containers:
        - name: laravel-web
          image: ingchhy/laravel-app:latest   # <-- changed here
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "laravel"
            - name: DB_USERNAME
              value: "ING"
            - name: DB_PASSWORD
              value: "123"
          lifecycle:
            postStart:
              exec:
                command:
                  ["/bin/sh", "-c", "sleep 30 && php artisan migrate --force"]

        - name: mysql-db
          image: mysql:5.7                        # <-- changed here
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
            - name: MYSQL_DATABASE
              value: "laravel"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
