apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
  selector:
    app: laravel-app
